services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # FORCE THE FULL PATH:
      - ${PWD}:/app
      - /app/.venv
      - /app/__pycache__

    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./vending.db